import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav className="flex gap-4 ps-4 px-4 bg-cyan-950 text-white font-bold text-xl">
                    <Link className="hover:text-indigo-100" href={'/'}>
                        Home
                    </Link>
                    <Link className="hover:text-indigo-100" href={'/tags'}>
                        Tags
                    </Link>
                </nav>

                {children}
            </body>
        </html>
    );
}
